# This is a basic workflow to help you get started with Actions

name: Docker Image CI  # workflow名称，可以随意改

# Controls when the workflow will run
on: # workflow的事件钩子，告知程序说明时候出发自动部署
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ] # 在master分支有push操作的时候自动部署
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: autotelic/action-wait-for-status-check@v1
      id: wait-for-status
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        statusName: "An Expected Commit Status Context"
    - name: Do something with a passing status
      if: steps.wait-for-status.outputs.state == 'success'
    - name: Do something with a failing status
      if: steps.wait-for-status.outputs.state == 'failure'
    - name: Echo Outputs
      run: |
       echo ${{ steps.wait-for-status.outputs.context }}
       echo ${{ steps.wait-for-status.outputs.state }}
       echo ${{ steps.wait-for-status.outputs.description }}
       echo ${{ steps.wait-for-status.outputs.target_url }}
  # This workflow contains a single job called "build"
  build: # 打包并上传docker镜像
    needs: [check]
    runs-on: ubuntu-latest # 依赖的环境      
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
      # ${{ secrets.DOCKER_REPOSITORY }}是读取之前在Secret创建的名为DOCKER_REPOSITORY的值
        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:1.0 ./ # 打包并docker镜像，版本为latest
      - name: Login to Registry # 登录阿里云镜像服务器
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      - name: Push Image # 推送镜像，设置版本为latest
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:1.0
