# This is a basic workflow to help you get started with Actions

name: Docker Image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        # ${{ secrets.DOCKER_REPOSITORY }}是读取之前在Secret创建的名为DOCKER_REPOSITORY的值
        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest ./ # 打包并docker镜像，版本为latest
      - name: Login to Registry # 登录阿里云镜像服务器
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      - name: Push Image # 推送镜像，设置版本为latest
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
  pull-docker: # docker部署
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.2.140 # 服务器ip
          username: root # 服务器登录用户名
          password: 123456 # 服务器登录密码
          port: 22 # 服务器ssh端口
          script: |
            # 停止旧版容器
            docker stop $(docker ps --filter ancestor=registry.cn-hangzhou.aliyuncs.com/testdhczhang/testhelloworld -q)
            # 删除旧版容器
            docker rm -f $(docker ps -a --filter ancestor=registry.cn-hangzhou.aliyuncs.com/testdhczhang/testhelloworld:latest -q)
            # 删除旧版镜像
            docker rmi -f $(docker images registry.cn-hangzhou.aliyuncs.com/testdhczhang/testhelloworld:latest -q)
            # 登录阿里云镜像服务器
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
            # 拉取最新latest版本镜像
            docker pull registry.cn-hangzhou.aliyuncs.com/testdhczhang/testhelloworld:latest
            # 运行最新latest版本镜像
            docker run -d -p 8080:80 docker pull registry.cn-hangzhou.aliyuncs.com/testdhczhang/testhelloworld:latest
