# This is a basic workflow to help you get started with Actions

name: Docker Image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  pull-docker: # docker部署
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: csexton/debugger-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME  }}
          password: ${{ secrets.HOST_PASSWORD  }}
          port: ${{ secrets.HOST_PORT }}
          script: whoami
