# This is a basic workflow to help you get started with Actions

name: Deploy to Amazon ECS（CICD）  # workflow名称，可以随意改

# Controls when the workflow will run
on:                                      # workflow的事件钩子，告知程序说明时候出发自动部署
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master]                 # 在master分支有push操作的时候自动部署
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Check:
    name: check
    runs-on: ubuntu-latest
    steps:
    - name: Check commit status
      id: commit-status
      run: |
        # Check the status of the Git commit
        CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}' | jq -r '.state');
        echo "Current status is: $CURRENT_STATUS"
        if [ "${CURRENT_STATUS^^}" = "PENDING" ]; 
          then echo "Commit status PENDING!"; 
          exit 0; 
        fi
        if [ "${CURRENT_STATUS^^}" = "SUCCESS" ]; 
          then echo "Commit status SUCCESS!"; 
          exit 0; 
        fi
        if [ "${CURRENT_STATUS^^}" = "FAILURE" ]; 
          then echo "Commit status failed. Canceling execution"; 
          exit 1; 
        fi
  build: # 打包并上传docker镜像
    needs: [Check]
    runs-on: ubuntu-latest # 依赖的环境      
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
      # ${{ secrets.DOCKER_REPOSITORY }}是读取之前在Secret创建的名为DOCKER_REPOSITORY的值
        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest ./ # 打包并docker镜像，版本为latest
      - name: Login to Registry # 登录阿里云镜像服务器
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      - name: Push Image # 推送镜像，设置版本为latest
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
  pull-docker: # docker部署
      needs: [build]
      name: Pull Docker
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }} # 服务器ip
            username: ${{ secrets.HOST_USERNAME }} # 服务器登录用户名
            key: ${{ secrets.HOST_SSHKEY }} # 服务器登录Key
            port: ${{ secrets.HOST_PORT }} # 服务器ssh端口
            script: |
              whoami
              ls -la
              # 停止旧版容器
              # sudo docker stop ${{ secrets.DOCKER_REPOSITORY }}
              # 删除旧版容器
              # sudo docker rm ${{ secrets.DOCKER_REPOSITORY }}
              # 删除旧版镜像
              # sudo docker rmi ${{ secrets.DOCKER_REPOSITORY }}:latest
              # 登录阿里云镜像服务器
              # sudo docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
              # 拉取最新latest版本镜像
              # sudo docker pull ${{ secrets.DOCKER_REPOSITORY }}:latest
              # 运行最新latest版本镜像
              # sudo docker run -d -p 88:80 ${{ secrets.DOCKER_REPOSITORY }}:latest
